#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30
  config:
    activate:
      on-profile:
  web:
    resources:
      add-mappings: true

server:
  port: 8080
  tomcat:
    accessors:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
    operations-sorter: method
    #custom path for api docs
    url: /doc/openapi.json