{
 "title": "JMeter_Prometheus_Grafana",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,15m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_count_total{})" }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_failure_total{})" }
   ]
  },
  {
   "title": "Failure Rate %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(jmeter_failure_total[$interval]))/sum(rate(jmeter_count_total[$interval])))"
    }
   ]
  },
  {
   "title": "Load Test Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_count_total[$interval]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(jmeter_summary{})" }
   ]
  },
  {
   "title": "90th Percentile  Response Time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jmeter_summary{quantile=\"0.9\"})"
    }
   ]
  },
  {
   "title": "Jmeter Aggregate Report",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(label)(jmeter_count_total{})"
    },
    {
     "expr": "avg(jmeter_summary{}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.9\"}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.95\"}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{quantile=\"0.99\"})"
    },
    {
     "expr": "min(jmeter_summary{}) by (label)"
    },
    {
     "expr": "max(jmeter_summary{}) by (label)"
    },
    {
     "expr": "(sum(rate(jmeter_failure_total[$__interval]))/sum(rate(jmeter_count_total[$__interval]))) * 100",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sum(rate(jmeter_count_total[$__interval])) by (label)"
    },
    {
     "expr": "avg(jmeter_rsize_sum{}/1024) by (label)"
    },
    {
     "expr": "avg(jmeter_rsize_count{}/1024) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(jmeter_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Response times by Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jmeter_summary{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "90th Pct response times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jmeter_summary{quantile=\"0.9\"}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Requests per second by Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_count_total[$interval])) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Errors Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error by Transactions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (code,label) (jmeter_failure_total)"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (code) (jmeter_failure_total)"
    }
   ]
  },
  {
   "title": "Test farm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC % time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}} "
    }
   ]
  },
  {
   "title": "JVM heap  - free memory by pool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM heap -  used memory by pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  }
 ]
}